### ISSUE TITLE
Custom Tensorflow model

### ISSUE THREAD

**Issue by MaximeLee** [IRT-SystemX/ml4physim_startingkit#12]
I would like to code a custom model in tensorflow. As of now, I only saw in your notebooks of to use your default `Fully Connected Augmented Simulator` in Tensorflow [4a_How_to_contribute_Tensorflow.ipynb](https://github.com/IRT-SystemX/ml4physim_startingkit/blob/main/4a_How_to_contribute_Tensorflow.ipynb). 

If I want to do a custom architecture, how should I proceed? Is it possible to have a template in order to implement my custom class/model architecture?

**Comment by daviddanan** [comment]
I think the easiest way would be to considered what we refered as "Advance users" way in section III in https://github.com/IRT-SystemX/ml4physim_startingkit/blob/main/4_How_to_contribute.ipynb
I am not saying it could not be done by using LIPS but there is much more boilerplate from my point of view.

You can see a complete example of that here
https://github.com/IRT-SystemX/ml4physim_startingkit/blob/main/3b_Reproduce_baseline_result_advanced_configuration.ipynb
