### ISSUE TITLE
[Doc] Number of targets

### ISSUE THREAD

**Issue by Bulbille** [IRT-SystemX/ml4physim_startingkit#3]
1_Airfoils_design_basic_simulation.ipynb

> Each point is given a target of 5 components for the underyling regression task:
> 
> * the velocity (two components in meter per second)
> * the pressure divided by the specific mass (one component in meter squared per second squared)
> * the turbulent kinematic viscosity (one component in meter squared per second)
> * a boolean is attached to each point to inform if this point lies on the airfoil or not.

3_Reproduce_baseline_result.ipynb

> Each point is given a target of 4 components for the underlying regression task:
> - the velocity (two components in meter per second): 'x-velocity'and 'y-velocity'
> - the pressure divided by the specific mass (one component in meter squared per second squared): 'pressure'
> - the turbulent kinematic viscosity (one component in meter squared per second): 'turbulent_viscosity'

The notebooks are not consistent in the number of target components

**Comment by daviddanan** [comment]
Indeed, you are right, this is slightly misleading.

The boolean attached to each point is used for the usecase but it is not a component in the regression task. It will be corrected in the next commit. Thank you.

Closing the issue.
